version: '3.8'

services:
  sales-buddy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_PATH=/app/data/entities.db
      - AI_PROVIDER=openai
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RATE_LIMIT_ENABLED=true
      - RATE_LIMIT_WINDOW_MINUTES=15
      - RATE_LIMIT_MAX_REQUESTS=100
    volumes:
      - sales_buddy_data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - sales_buddy_network

volumes:
  sales_buddy_data:
    driver: local

networks:
  sales_buddy_network:
    driver: bridge 