name: voice-entity-app

services:
  - name: api
    git:
      url: https://github.com/DealExMachina/voice-entity-recog-proto
      branch: main
    ports:
      - port: 8000
        protocol: http
    env:
      - name: NODE_ENV
        value: production
      - name: PORT
        value: "8000"
      - name: DB_PATH
        value: "/tmp/entities.db"
      - name: RATE_LIMIT_ENABLED
        value: "true"
      - name: RATE_LIMIT_WINDOW_MINUTES
        value: "15"
      - name: RATE_LIMIT_MAX_REQUESTS
        value: "100"
      - name: AI_PROVIDER
        value: "openai"
      - name: OPENAI_API_KEY
        from_secret: OPENAI_API_KEY
      - name: MISTRAL_API_KEY
        from_secret: MISTRAL_API_KEY
    build:
      buildpack: nodejs
    regions:
      - fra
    scale:
      min: 1
      max: 1
    lifecycle:
      health_check:
        http:
          path: /api/health
          port: 8000
      restarts:
        policy: on_failure
        max_count: 3 